config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  resources :users, only: [:index, :show, :edit, :update, :new, :create]
  root to: "pages#home"

  get 'tools/:id/blockages_history', to: 'tools#blockages_history'
  get 'tools/production', to: 'tools#production'
  get 'blockages/active', to: 'blockages#active'
  # #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tools, only: [:index, :new, :create, :show, :edit, :update] do
    resources :cavities, only: [:new, :create]
    resources :production_orders, only: [:new, :create]
    resources :blockages, only: [:new, :create]
    resources :wash_orders, only: [:new, :create]
    resources :damage_reports, only: [:new, :create]
    get 'blockages_history', to: 'tools#blockages_history'
  end

  resources :production_orders, only: [:edit, :update]

  resources :cavities, only: [:edit, :update, :show, :destroy]

  resources :wash_orders, only: [:index, :show, :edit, :update]
  get 'wash_orders/:id/manual_process', to: 'wash_orders#manual_process', as: 'manual_process'

  resources :damage_reports, only: [:index, :show, :edit, :update]

  resources :blockages, only: [:index, :show, :edit, :update]

end

app/models/tool.rb
require 'csv'

class Tool < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_params,
      against: [:alias, :sap, :customer, :location, :bu, :segment, :technology],
      using: {
      tsearch: { prefix: true }
      }
  has_many :cavities
  has_many :wash_orders
  has_many :blockages
  has_many :production_orders
  has_many :damage_reports
  validates(
    :alias,
    :sap,
    :capacity,
    :technology,
    :segment,
    :bu,
    :volume,
    :customer,
    :damaged,
    :blocked,
    :active,
    :spares,
    presence: true
  )
  has_one_attached :layout
  validate :layout_mime_type

  def update_available
    if capacity === 0
      update(available: nil)
    else
      result = (active * 100) / capacity.to_f
      update(available: result.round(2))
    end
  end

  def open_orders_without_process_end?
    wash_orders.any? { |order| order.status == "open" } &&
      manual_process &&
      wash_orders.find_by(status: "open")&.manual_process_start &&
      wash_orders.find_by(status: "open")&.manual_process_end.nil?
  end

  def open_orders_without_process_start?
    wash_orders.any? { |order| order.status == "open" } &&
      manual_process &&
      wash_orders.find_by(status: "open")&.manual_process_start.nil?
  end

  def open_wash_order
    wash_orders.find_by(status: "open")
  end

  def active_wash_order?
    if wash_orders.where(status: "open").count == 0
      return true
    else
      return false
    end
  end

  private

  def layout_mime_type
    return unless layout.attached?
    if layout.attached? && !layout.content_type.in?(%w(application/pdf))
      errors.add(:layout, 'must be a PDF')
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = policy_scope(Tool)
    if params[:query].present?
      @query = params[:query]
      @tools = Tool.search_by_params(@query).order(location: :asc)
    else
      @tools = Tool.all.order(location: :asc)
    end
    respond_to do |format|
      format.html
      format.csv { send_data to_csv(@tools), filename: "tools-#{Time.now.strftime('%y%m%d')}.csv" }
    end
    @average_availability = Tool.all.average(:available)&.round(2) || 0
    @hv_availability = Tool.where(segment: "HV").average(:available)&.round(2) || 0
    @mv_availability = Tool.where(segment: "MV").average(:available)&.round(2) || 0
    @lv_availability = Tool.where(segment: "LV").average(:available)&.round(2) || 0
  end

  def blockages_history
    @tool = Tool.find(params[:id])
    authorize @tool
    @tool_blockages = @tool.blockages.order(id: :desc)
  end

  def production
    if params[:query].present?
      @tools = Tool.search_by_params(params[:query]).where(location: "production").or(Tool.where(location: "washing")).order(location: :desc)
    else
      @tools = Tool.where(location: "production").or(Tool.where(location: "washing")).order(location: :desc)
    end
    authorize @tools
    @wash_orders_in_process = WashOrder.where(status: "open").count
  end

  def show
    @tool = Tool.find(params[:id])
    authorize @tool
    @cavity = Cavity.new
    @cavities = @tool.cavities.order(status: :asc)
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    authorize @tool
    set_tool_values
    if @tool.save
      redirect_to tool_path(@tool)

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tool = Tool.find(params[:id])
    authorize @tool
  end

  def update
    @tool = Tool.find(params[:id])
    authorize @tool
    if @tool.update(tool_params)
      @tool.update_available
      @tool.update(last_updated_by:"#{current_user.id}-#{current_user.name} #{current_user.lastname}")
      redirect_to tool_path(@tool)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:alias, :sap, :capacity, :technology, :bu, :volume,
                                 :customer, :capacity, :segment, :layout, :manual_process)
  end

  def set_tool_values
    @tool.created_by = "#{current_user.id}-#{current_user.name} #{current_user.lastname}"
    @tool.last_updated_by = @tool.created_by
    @tool.active = 0
    @tool.damaged = 0
    @tool.blocked = 0
    @tool.spares = 0
    @tool.plant = current_user.plant
    @tool.location = "stored"
  end

  def to_csv(tools)
    attribs = [:id, :alias, :sap, :plant, :bu, :technology, :volume, :customer,
               :capacity, :location, :damaged, :blocked, :active, :spares, :segment, :available]
    CSV.generate(headers: true) do |csv|
      csv << attribs
      tools.each do |tool|
        csv << attribs.map{ |attr| tool.send(attr) }
      end
    end
  end
end

app/views/tools/blockages_history.html.erb
<div class="mx-3 my-3">
    <% if @tool_blockages.empty? %>
      <h1 class= "fw-bold text-center">No Blockages Found</h1>
    <% else %>
      <div class="scroll-container rounded-4 bg-light">
        <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary rounded centered-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>T_SAP</th>
              <th>T_Alias</th>
              <th>Cavity_num</th>
              <th>Created_by</th>
              <th>Date</th>
              <th>Time</th>
              <th>Reason</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% @tool_blockages.each do |blockage| %>
            <tr>
              <td><%= blockage.id %></td>
              <td><%= blockage.tool.sap %></td>
              <td><%= blockage.tool.alias %></td>
              <td><%= blockage.cavity.num %></td>
              <td><%= blockage.created_by %></td>
              <td><%= blockage.created_at.in_time_zone('America/Mexico_City').strftime('%m-%d-%y')  %></td>
              <td><%= blockage.created_at.in_time_zone('America/Mexico_City').strftime('%H:%M:%S') %></td>
              <td><%= blockage.reason %></td>
              <td><%= blockage.status %></td>
              <td>
                <%= link_to blockage_path(blockage) do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <div>
    <% end %>
</div>

app/views/tools/edit.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Edit Tool</h1>
  <div class="registration-form">
    <%= simple_form_for @tool do |f| %>
      <%= f.input :alias, required: true %>
      <%= f.input :sap, required: true  %>
      <%= f.input :technology, reuired: true  %>
      <%= f.input :bu, required: true  %>
      <%= f.input :volume, required: true  %>
      <%= f.input :segment, required: true, hint: 'LV 1000 to 9,900 / MV 10,000 to 39,900 / HV 40,000+',
      collection: ['HV', 'MV', 'LV']%>
      <%= f.input :customer, required: true  %>
      <%= f.input :capacity, required: true%>
      <%= f.input :manual_process, label:"Requires manual washing or disassembly" %>
      <%= f.input :layout, label:'New_file', as: :file , hint: 'PDF file'%>
      <div class="form-alert p-3 my-3">
        <p><strong>Blocked:</strong> <%= @tool.blocked %></p>
        <p><strong>Damaged:</strong> <%= @tool.damaged %></p>
        <p style="font-size:14px;"> *These values are updated based on blockages</p>
      </div>
      <div class="d-flex justify-content-between">
        <%= f.button :submit, class:"btn btn-primary mb-3" %>
        <%= link_to "cancel", tool_path(@tool),class:"btn btn-primary mb-3" %>
      </div>
    <% end %>
  </div>e
</div>

app/views/tools/index.html.erb
<div class="mt-2 mx-4">
  <div>
    <div class="cards my-5">
      <% if @hv_availability <= 70 %>
        <div class="card-category row text-center mx-1 bg-danger">
      <% elsif @hv_availability < 90 %>
        <div class="card-category row text-center mx-1 bg-warning">
      <% else %>
        <div class="card-category row text-center mx-1 bg-success">
      <% end %>
          <div class="col align-self-center">
            <h1 class="fw-bold"><%= @hv_availability.round(2) %>%</h1>
            <p class="fw-bold">HV Availability</p>
          </div>
        </div>
      <% if @mv_availability <= 70 %>
        <div class="card-category row text-center mx-1 bg-danger">
      <% elsif @mv_availability < 90 %>
        <div class="card-category row text-center mx-1 bg-warning">
      <% else %>
        <div class="card-category row text-center mx-1 bg-success">
      <% end %>
          <div class="col align-self-center">
            <h1 class="fw-bold"><%= @mv_availability.round(2) %>%</h1>
            <p class="fw-bold">MV Availability</p>
          </div>
        </div>
      <% if @lv_availability <= 70 %>
        <div class="card-category row text-center mx-1 bg-danger">
      <% elsif @lv_availability < 90 %>
        <div class="card-category row text-center mx-1 bg-warning">
      <% else %>
        <div class="card-category row text-center mx-1 bg-success">
      <% end %>
          <div class="col align-self-center">
            <h1 class="fw-bold"><%= @lv_availability.round(2) %>%</h1>
            <p class="fw-bold">LV Availability</p>
          </div>
        </div>
    </div>
  </div>
  <% if @tools.empty? %>
    <div class="my-3">
      <h1 class="fw-bold text-center">No tools found</h1>
    </div>
  <% else %>
    <div class="row justify-content-end">
      <div class="col-lg-4 col-md-6 my-2">
        <%= form_with url: tools_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Type a keyword"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-between mb-2">
      <h3 class="mb-0 align-self-end fw-bold">Availability <%= @average_availability.round(2) %>%</h3>
      <%= link_to "Export Tools CSV", tools_path(query: @query, format: :csv), class:"btn btn-primary btn-sm align-self-end" %>
    </div>
    <div class="scroll-container rounded-4 bg-light">
        <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary rounded centered-table">
          <thead>
            <tr>
              <th>Alias</th>
              <th>SAP</th>
              <th><i class="fa-sharp fa-solid fa-paperclip"></i></th>
              <th>Plant</th>
              <th>BU</th>
              <th>Tech</th>
              <th>Volume</th>
              <th>Customer</th>
              <th>Location</th>
              <th>Dmg</th>
              <th>Blk</th>
              <th>Act</th>
              <th>Spr</th>
              <th>Seg</th>
              <th>Avail%</th>
            </tr>
          </thead>
          <tbody>
          <% @tools.each do |tool| %>
          <tr>
          <td>
          <%= link_to tool_path(tool), class:"link-blue" do %>
          <%= tool.alias %>
          <% end %>
          </td>
          <td><%= tool.sap %></td>
          <td class="text-center">
            <% if tool.layout.present?%>
              <%= link_to tool.layout , :target => "_blank" do %>
                <i class="fa-sharp fa-solid fa-paperclip" style="color: #005eff;"></i>
              <% end %>
              <% else %>
                <i class="fa-solid fa-ban" style="color: #989aa0;"></i>
            <% end %>
          </td>
          <td><%= tool.plant%></td>
          <td><%= tool.bu %></td>
          <td><%= tool.technology %></td>
          <td><%= tool.volume %></td>
          <td><%= tool.customer %></td>
          <% if tool.location === "production" %>
            <% if policy(ProductionOrder).edit? %>
              <td><%= link_to "produc", edit_production_order_path(tool.production_orders.find_by(status:"open")), class: "btn btn-primary"%></td>
            <% else %>
              <td><span class= "bg-primary p-2 fw-medium" style="color: white;" >produc</span></td>
            <% end %>
          <% elsif tool.location === "washing" %>
            <td><span class= "bg-warning p-2">washing</span></td>
          <% elsif tool.location === "stored" %>
            <% if policy(ProductionOrder).create? %>
              <td><%= link_to tool.location, new_tool_production_order_path(tool), class: "btn btn-success"%></td>
            <% else %>
              <td><span class= "bg-success p-2 fw-medium" >stored</span></td>
            <% end %>
          <% end %>
          <td>
          <%= tool.damaged %>
          <% if policy(Blockage).create? %>
            <%= link_to new_tool_blockage_path(tool) do %>
            <i class="fa-solid fa-square-plus"></i>
            <% end %>
          <% end %>
          </td>
          <td>
          <%= tool.blocked %>
          <% if policy(Blockage).create? %>
            <%= link_to new_tool_blockage_path(tool) do %>
            <i class="fa-solid fa-square-plus"></i>
            <% end %>
          <% end %>
          </td>
          <td><%= tool.active %></td>
          <td><%= tool.spares %></td>
          <td><%= tool.segment %></td>
          <td><%= tool.available %>%</td>
          </tr>
          <% end %>
          </tbody>
        </table>
    </div>
  <% end %>
</div>

app/views/tools/new.html.erb
<div class="container my-3">
  <div class="registration-form">
    <%= simple_form_for @tool do |f| %>
        <%= f.input :alias, inline_label:'Alias' , required: true %>
        <%= f.input :sap, required: true  %>
        <%= f.input :technology, reuired: true  %>
        <%= f.input :bu, required: true, collection: [ "Damper" ,"Steering", "Low_Volume"]  %>
        <%= f.input :volume, required: true  %>
        <%= f.input :segment, required: true, hint: 'LV 1000 to 9,900 / MV 10,000 to 39,900 / HV 40,000+',
        collection: ['HV', 'MV', 'LV']%>
        <%= f.input :customer, required: true  %>
        <%= f.input :capacity, required: true, label:"Cavities Capacity"%>
        <%= f.input :manual_process, label:"Requires manual washing or disassembly" %>
        <%= f.input :layout, as: :file , hint: 'PDF file'%>
        <%= f.button :submit, class:"btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/tools/production.html.erb
<div class="mt-2 mx-4">
  <div class="row justify-content-end">
    <div class="col-lg-4 col-md-6 my-2">
      <%= form_with url: tools_production_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <h3 class= "fw-bold my-3" >
    <span class="p-2 rounded" style= "background-color:#ffe591;">
      Wash Orders in Process: <%= @wash_orders_in_process %>
    </span>
  </h3>
  <div class="cards-production">
  <% @tools.each do  |tool|%>
        <div class="card shadow p-3 m-1 bg-body-tertiary rounded card-category" style="height: 25rem">
          <div class="card-header">
            <div class="row justify-content-between">
              <div class="col-auto"><strong>Alias:</strong> <%= tool.alias %></div>
              <% if tool.location === "washing" %>
              <div class="col-auto text-end bg-info fw-bold" style="font-size: small;">washing <i class="fa-solid fa-soap"></i></div>
              <% elsif tool.location === "production" %>
              <div class="col-auto text-end" style="font-size: large;"><i class="fa-sharp fa-solid fa-gears" style="color: #1f6ff9;"></i></i></div>
              <% end %>
            </div>
            <p><strong>SAP:</strong> <%= tool.sap %></p>
          </div>
          <div class="card-body overflow-auto">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <strong>Blocked:</strong>
                    <% if tool.blockages.present? %>
                      <%= tool.blockages.select { |b| b.status === 'open' && b.reason === "wash" }.map { |b| b.cavity.num }.join(", ") %>
                    <% end %>
                </li>
                <li class="list-group-item">
                  <strong>Damaged:</strong>
                    <% if tool.blockages.present? %>
                      <%= tool.blockages.select { |b| b.status === 'open' && b.reason === "damaged" }.map { |b| b.cavity.num }.join(", ") %>
                    <% end %>
                </li>
                <% if tool.location === "washing" %>
                  <li class="list-group-item">
                      <strong>WO Comments:</strong>
                      <%= tool.open_wash_order.comments %>
                  </li>
                <% end %>
              </ul>
          </div>
          <div class="card-footer">
            <% if policy(WashOrder).create? %>
              <% if tool.wash_orders.any?{|order| order.status == "open"} %>
                <% classes = "btn btn-sm btn-warning fw-bold"
                classes += " disabled" if tool.open_wash_order.active_sub_process %>
                <%= link_to "update", edit_wash_order_path(tool.open_wash_order), class:classes%>
              <% else %>
                <%= link_to "start_wash", new_tool_wash_order_path(tool), class:"btn btn-sm btn-primary fw-bold" %>
              <% end %>
            <% end %>
            <% if policy(Blockage).create? %>
              <%= link_to "Block_Cav", new_tool_blockage_path(tool), class: "btn btn-sm btn-danger fw-bold ms-auto" %>
            <% end %>
            <% if policy(DamageReport).create? %>
              <%= link_to "Report_DMG", new_tool_damage_report_path(tool), class: "btn btn-sm btn-info fw-bold ms-auto" %>
            <% end %>
            <% if tool.open_orders_without_process_start? %>
                <%= link_to "Start_Sub_process", manual_process_path(tool.open_wash_order), method: :patch, class:"btn btn-sm btn-success fw-bold" %>
            <% elsif tool.open_orders_without_process_end? %>
              <%= link_to "End_Sub_process", manual_process_path(tool.open_wash_order), method: :patch, class:"btn btn-sm btn-danger fw-bold" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tools/show.html.erb
<div class="container my-3">
  <div class="mx-auto border border-secondary-subtle
      shadow p-5 mb-5 bg-light rounded-4">
      <h1 class="text-center fw-bold">Tool Info</h1>
      <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary">
        <tr>
          <td class="fw-bold">
           ID
          </td>
          <td>
            <%= @tool.id %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Alias
          </td>
          <td>
            <%= @tool.alias %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           SAP
          </td>
          <td>
            <%= @tool.sap %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Plant
          </td>
          <td>
            <%= @tool.plant %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           BU
          </td>
          <td>
            <%= @tool.bu %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Technology
          </td>
          <td>
            <%= @tool.technology %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Volume
          </td>
          <td>
            <%= @tool.volume %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Customer
          </td>
          <td>
            <%= @tool.customer %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Cavities capacity
          </td>
          <td>
            <%= @tool.capacity %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Location
          </td>
          <td>
            <%= @tool.location %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Damaged cavities
          </td>
          <td>
            <%= @tool.damaged %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Blocked cavities
          </td>
          <td>
            <%= @tool.blocked %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Active cavities
          </td>
          <td>
            <%= @tool.active %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Spare cavities
          </td>
          <td>
            <%= @tool.spares %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Manual process
          </td>
          <td>
            <% if @tool.manual_process%>
              <span class="bg-warning p-1 rounded">Required</span>
            <% else %>
              Not required
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Segment
          </td>
          <td>
            <%= @tool.segment %>
          </td>
        </tr>
        <tr>
          <td class="fw-bold">
           Available %
          </td>
          <td>
            <%= @tool.available %>%
          </td>
        </tr>
          <td class="fw-bold">
           Layout
          </td>
          <td>
            <% if @tool.layout.present? %>
              <%= link_to @tool.layout , :target => "_blank" do %>
                <i class="fa-sharp fa-solid fa-paperclip" style="color: #005eff;"></i>
              <% end %>
            <% else %>
              <i class="fa-solid fa-ban" style="color: #989aa0;"></i>
            <% end %>
          </td>
        </tr>
        <tr>
        <td class="fw-bold">
        Active Cavities:
        </td>
        <td>
          <% if @tool.cavities %>
            <%= @tool.cavities.select { |c| c.status === 'released' && !c.is_spare }.map { |c| c.num }.join(", ") %>
          <% end %>
        </td>
        </tr>
        <tr>
        <td class="fw-bold">
        Unavail Cavities:
        </td>
        <td>
          <% if @tool.cavities %>
            <%= @tool.cavities.select { |c| c.status == 'unavail' }.map { |c| c.num }.join(", ") %>
          <% end %>
        </td>
        </tr>
        <tr>
        <td class="fw-bold">
        Spare Cavities:
        </td>
        <td>
          <% if @tool.cavities %>
            <%= @tool.cavities.select { |c| c.is_spare }.map { |c| c.num }.join(", ") %>
          <% end %>
        </td>
        </tr>
        <tr>
          <td style="font-size: 12px;">
            Created by:
          </td>
          <td><%= @tool.created_by %></td>
        </tr>
        <tr>
          <td style="font-size: 12px;">
            Updated by:
          </td>
          <td><%= @tool.last_updated_by %></td>
        </tr>
      </table>
      <% if policy(@tool).edit? %>
        <%= link_to "Edit_Tool", edit_tool_path(@tool), class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Blockages_History", tool_blockages_history_path(@tool), class: "btn btn-secondary" %>
      <% if policy(Blockage).create? %>
        <%= link_to "Block_Cav", new_tool_blockage_path(@tool), class: "btn btn-danger" %>
      <% end %>
      <% if policy(DamageReport).create? %>
       <%= link_to "Report_DMG", new_tool_damage_report_path(@tool), class: "btn btn-info" %>
      <% end %>
  </div>
  <div class="mx-auto border border-secondary-subtle shadow p-5 mb-5 bg-light rounded-4">
    <h1 class="text-center fw-bold">Cavities</h1>
      <% if policy(@cavity).new? %>
        <div class="col-6 mx-auto">
          <%= simple_form_for [@tool,@cavity] do |f| %>
            <%= f.input :num , require: true %>
            <%= f.input :status, require: true, collection: ["released", "unavail"] %>
            <%= f.input :comments %>
            <%= f.input :is_spare, label: "Is spare" %>
            <%= f.button :submit, "Add_Cavity", class:"btn btn-primary mb-3" %>
          <% end %>
        </div>
      <% end %>
    <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary text-center">
      <thead>
        <tr>
          <th>Cavity Number</th>
          <th>Cavity Status</th>
          <th>Spare</th>
          <th>Created_By</th>
          <th>Updated_By</th>
          <th>View</th>
        </tr>
      </thead>
  <% if !@tool.cavities.empty? %>
      <tbody>
        <% if @cavities %>
          <% @cavities.each do |cavity| %>
            <tr>
              <td><%= link_to cavity.num, cavity_path(cavity) %></td>
              <td>
              <% if policy(Blockage).edit? && (cavity.status == "blocked" || cavity.status == "damaged")  %>
                <%= link_to edit_blockage_path(cavity.blockages.find_by(status: "open")) do %>
                  <%= cavity.status %>
                <% end %>
              <% else %>
                <%= cavity.status %>
              <% end %>
              </td>
              <td><%= cavity.is_spare ? 'Yes' : 'No' %></td>
              <td><%= cavity.created_by %></td>
              <td><%= cavity.last_updated_by %></td>
              <td>
                <%= link_to cavity_path(cavity) do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
  </div>
</div>