config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  resources :users, only: [:index, :show, :edit, :update, :new, :create]
  root to: "pages#home"

  get 'tools/:id/blockages_history', to: 'tools#blockages_history'
  get 'tools/production', to: 'tools#production'
  get 'blockages/active', to: 'blockages#active'
  # #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tools, only: [:index, :new, :create, :show, :edit, :update] do
    resources :cavities, only: [:new, :create]
    resources :production_orders, only: [:new, :create]
    resources :blockages, only: [:new, :create]
    resources :wash_orders, only: [:new, :create]
    resources :damage_reports, only: [:new, :create]
    get 'blockages_history', to: 'tools#blockages_history'
  end

  resources :production_orders, only: [:edit, :update]

  resources :cavities, only: [:edit, :update, :show, :destroy]

  resources :wash_orders, only: [:index, :show, :edit, :update]
  get 'wash_orders/:id/manual_process', to: 'wash_orders#manual_process', as: 'manual_process'

  resources :damage_reports, only: [:index, :show, :edit, :update]

  resources :blockages, only: [:index, :show, :edit, :update]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg py-0 navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class:"navbar-brand" do %>
    <%= image_tag "Logo_Navbar",
    alt:"Logo", height:"40", class:"d-inline-block align-text-top"%>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if user_signed_in? %>
      <div class="navbar-nav">
        <div class="nav-item dropdown">
          <a class="nav-link <%=' active' if current_page?(tools_path) || current_page?(tools_production_path) || current_page?(new_tool_path)%>
          dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tools
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", tools_path, class: "nav-link#{' active' if current_page?(tools_path)}" %></li>
            <li><%= link_to "Production", tools_production_path , class: "nav-link#{' active' if current_page?(tools_production_path)}" %></li>
            <% if policy(Tool).new? %>
              <li><%= link_to "New_Tool", new_tool_path, class: "nav-link#{' active' if current_page?(new_tool_path)}" %></li>
            <% end %>
          </ul>
        </div>
        <div class="nav-item dropdown">
          <a class="nav-link <%=' active' if current_page?(blockages_path) || current_page?(blockages_active_path)%> dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Blockages
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", blockages_path, class: "nav-link#{' active' if current_page?(blockages_path)}" %></li>
            <li><%= link_to "Active", blockages_active_path, class: "nav-link#{' active' if current_page?(blockages_active_path)}" %></li>
          </ul>
        </div>
        <%= link_to "Wash_Orders", wash_orders_path, class: "nav-link#{' active' if current_page?(wash_orders_path)}" %>
        <%= link_to "Damage_Reports", damage_reports_path, class: "nav-link#{' active' if current_page?(damage_reports_path)}" %>
        <% if policy(User).index? %>
          <%= link_to "Users", users_path, class: "nav-link#{' active' if current_page?(users_path)}" %>
        <% end %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
      </div>
    <% else %>
      <div class="navbar-nav">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>
    </div>
  </div>
</div>