config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  resources :users, only: [:index, :show, :edit, :update, :new, :create]
  root to: "pages#home"

  get 'tools/:id/blockages_history', to: 'tools#blockages_history'
  get 'tools/production', to: 'tools#production'
  get 'blockages/active', to: 'blockages#active'
  # #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tools, only: [:index, :new, :create, :show, :edit, :update] do
    resources :cavities, only: [:new, :create]
    resources :production_orders, only: [:new, :create]
    resources :blockages, only: [:new, :create]
    resources :wash_orders, only: [:new, :create]
    resources :damage_reports, only: [:new, :create]
    get 'blockages_history', to: 'tools#blockages_history'
  end

  resources :production_orders, only: [:edit, :update]

  resources :cavities, only: [:edit, :update, :show, :destroy]

  resources :wash_orders, only: [:index, :show, :edit, :update]
  get 'wash_orders/:id/manual_process', to: 'wash_orders#manual_process', as: 'manual_process'

  resources :damage_reports, only: [:index, :show, :edit, :update]

  resources :blockages, only: [:index, :show, :edit, :update]

end

app/models/damage_report.rb
class DamageReport < ApplicationRecord
  has_many :damages
  belongs_to :tool
  has_many :blockages, through: :damages
  validates :quality, :machine_num, :shift, :operator, :bcl, :process_eng, :damaged_part, :description, :cause, presence: true
end

app/controllers/damage_reports_controller.rb
class DamageReportsController < ApplicationController
  before_action :set_tool, only: [:new, :create]

  def index
    @damage_reports = policy_scope(DamageReport)
    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      start_time = Time.new(start_date.year, start_date.month, start_date.day, 0, 0, 0, "+00:00")
      end_time = Time.new(end_date.year, end_date.month, end_date.day, 23, 59, 59, "+00:00")
    else
      today = (Time.now - 6.hours).to_date
      start_time = today.beginning_of_day
      end_time = today.end_of_day
    end
    start_time += 6.hours
    end_time += 6.hours
    @damage_reports = DamageReport.where(created_at: start_time..end_time).order(created_at: :asc)
  end

  def show
    @damage_report = DamageReport.find(params[:id])
    authorize @damage_report
  end

  def new
    @damage_report = DamageReport.new
    authorize @damage_report
  end

  def create
    @damage_report = DamageReport.new(damagereport_paramas)
    authorize @damage_report
    set_damage_report_values
    if @damage_report.save
      redirect_to damage_reports_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @damage_report = DamageReport.find(params[:id])
    authorize @damage_report
  end

  def update
    @damage_report = DamageReport.find(params[:id])
    authorize @damage_report
    if @damage_report.update(damagereport_paramas)
      if @damage_report.status == "close"
        @damage_report.update(
          closed_by: "#{current_user.name} #{current_user.lastname}"
        )
      end
      redirect_to damage_reports_path
      flash[:notice] = "Order updated succesfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def damagereport_paramas
    params.require(:damage_report).permit(:machine_num, :shift, :quality, :operator, :bcl, :process_eng, :damaged_part, :description, :cause, :comments, :status)
  end

  def set_tool
    @tool = Tool.find(params[:tool_id])
  end

  def set_damage_report_values
    @damage_report.tool = @tool
    @damage_report.created_by = "#{current_user.name} #{current_user.lastname}"
    @damage_report.status = "open"
  end
end

app/views/damage_reports/edit.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Edit Damage Report</h1>
  <div class="registration-form">
    <%= simple_form_for @damage_report do |f| %>
        <h2 class="text-center">Tool: <%= @damage_report.tool.alias %> </h2>
        <%= f.input :machine_num, label:"Machine_Number", require: true %>
        <%= f.input :shift, require: true %>
        <%= f.input :operator, require: true %>
        <%= f.input :quality, label:"Quality", require: true %>
        <%= f.input :bcl, label:"BCL", require: true %>
        <%= f.input :process_eng, label:"Process_Engineer", require: true %>
        <%= f.input :damaged_part, label:"Damaged_Part", require: true %>
        <%= f.input :description, label:"Incident_Description", require: true %>
        <%= f.input :cause, label:"Possible_Cause", require: true %>
        <%= f.input :comments, require: true %>
        <%= f.input :status, require: true, collection: ["open", "close"]%>
        <%= f.button :submit, "Update", class:"btn btn-primary mb-3 fw-bold" %>
    <% end %>
  </div>
</div>

app/views/damage_reports/index.html.erb
<div class="mx-3 my-3">
    <div class="row justify-content-end">
    <div class="col-lg-6 col-md-8 my-2">
      <form class="d-flex align-items-center">
        <label for="start_date">Start:</label>
        <input type="date" name="start_date" id="start_date" class="form-control mx-2">
        <label for="end_date">End:</label>
        <input type="date" name="end_date" id="end_date" class="form-control mx-2">
        <button type="submit" class="btn btn-primary">Filter</button>
      </form>
    </div>
    <p class= "text-end" style="font-size: 12px">*Today's reports, please enter dates for custom search.</p>
  </div>
  <% if @damage_reports.empty? %>
    <div class="my-3">
      <h1 class="fw-bold text-center">No Reports found</h1>
    </div>
  <% else %>
    <div class="scroll-container rounded-4 bg-light">
      <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary rounded centered-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Machine_num</th>
            <th>Operator</th>
            <th>Quality</th>
            <th>BCL</th>
            <th>Process_Eng</th>
            <th>Damage_Part</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @damage_reports.each do |report| %>
          <tr>
            <td><%= report.id %></td>
            <td><%= report.machine_num %></td>
            <td><%= report.operator %></td>
            <td><%= report.quality %></td>
            <td><%= report.bcl %></td>
            <td><%= report.process_eng %></td>
            <td><%= report.damaged_part %></td>
            <td><%= report.status %></td>
            <td>
            <%= link_to damage_report_path(report) do %>
            <i class="fa-solid fa-eye"></i>
            <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/damage_reports/new.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">New Damage Report</h1>
  <div class="registration-form">
    <%= simple_form_for [@tool, @damage_report] do |f| %>
        <h2 class="text-center">Tool: <%= @tool.alias %> </h2>
        <%= f.input :machine_num, label:"Machine_Number", require: true %>
        <%= f.input :shift, require: true %>
        <%= f.input :operator, require: true %>
        <%= f.input :quality, label:"Quality", require: true %>
        <%= f.input :bcl, label:"BCL", require: true %>
        <%= f.input :process_eng, label:"Process_Engineer", require: true %>
        <%= f.input :damaged_part, label:"Damaged_Part", require: true %>
        <%= f.input :description, label:"Incident_Description", require: true %>
        <%= f.input :cause, label:"Possible_Cause", require: true %>
        <%= f.input :comments, require: true %>
        <%= f.button :submit, "Create_Report", class:"btn btn-primary mb-3 fw-bold" %>
    <% end %>
  </div>
</div>

app/views/damage_reports/show.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Damage Report</h1>
  <div class="registration-form">
      <form action="">
        <h2 class="text-center">Tool: <%= @damage_report.tool.alias %> </h2>
        <p><strong>Machine_Number:</strong> <%= @damage_report.machine_num %></p>
        <p><strong>Shift:</strong> <%= @damage_report.shift %></p>
        <p><strong>Operator:</strong> <%= @damage_report.operator %></p>
        <p><strong>BCL:</strong> <%= @damage_report.bcl %></p>
        <p><strong>Process_Engineer:</strong> <%= @damage_report.process_eng %></p>
        <p><strong>Damaged_Part:</strong> <%= @damage_report.damaged_part %></p>
        <p><strong>Incident_Description:</strong> <%= @damage_report.description %></p>
        <p><strong>Possible_Cause:</strong> <%= @damage_report.cause %></p>
        <p><strong>Comments:</strong> <%= @damage_report.comments %></p>
        <p><strong>Status:</strong> <%= @damage_report.status %></p>
        <p><strong>Created_by:</strong> <%= @damage_report.created_by %></p>
        <p><strong>Closed_by:</strong> <%= @damage_report.closed_by %></p>
        <% if policy(@damage_report).edit? && @damage_report.status == "open" %>
          <%= link_to "Edit", edit_damage_report_path(@damage_report), class:"btn btn-primary fw-bold"%>
        <% end %>
    </form>
  </div>
</div>