config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  resources :users, only: [:index, :show, :edit, :update, :new, :create]
  root to: "pages#home"

  get 'tools/:id/blockages_history', to: 'tools#blockages_history'
  get 'tools/production', to: 'tools#production'
  get 'blockages/active', to: 'blockages#active'
  # #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tools, only: [:index, :new, :create, :show, :edit, :update] do
    resources :cavities, only: [:new, :create]
    resources :production_orders, only: [:new, :create]
    resources :blockages, only: [:new, :create]
    resources :wash_orders, only: [:new, :create]
    resources :damage_reports, only: [:new, :create]
    get 'blockages_history', to: 'tools#blockages_history'
  end

  resources :production_orders, only: [:edit, :update]

  resources :cavities, only: [:edit, :update, :show, :destroy]

  resources :wash_orders, only: [:index, :show, :edit, :update]
  get 'wash_orders/:id/manual_process', to: 'wash_orders#manual_process', as: 'manual_process'

  resources :damage_reports, only: [:index, :show, :edit, :update]

  resources :blockages, only: [:index, :show, :edit, :update]

end

app/models/wash_order.rb
require 'csv'

class WashOrder < ApplicationRecord
  belongs_to :tool
  validates :status, presence: true

  def formatted_time
    hours = time / 3600
    minutes = (time % 3600) / 60
    seconds = time % 60
    format('%02d:%02d:%02d', hours, minutes, seconds)
  end

  def formatted_wash_time
    hours = wash_time / 3600
    minutes = (wash_time % 3600) / 60
    seconds = wash_time % 60
    format('%02d:%02d:%02d', hours, minutes, seconds)
  end

  def active_sub_process
    return manual_process_start && manual_process_end.nil?
  end

  def total_time
    Time.current - created_at
  end

  def wash_time_minus_manual_process
    time - (manual_process_end - manual_process_start)
  end
end

app/controllers/wash_orders_controller.rb
class WashOrdersController < ApplicationController
  before_action :set_tool, only: [:new, :create]

  def index
    @wash_orders = policy_scope(WashOrder)
    if params[:start_date].present? && params[:end_date].present?
      @start_date = Date.parse(params[:start_date])
      @end_date = Date.parse(params[:end_date])
      start_time = Time.new(@start_date.year, @start_date.month, @start_date.day, 0, 0, 0, "+00:00")
      end_time = Time.new(@end_date.year, @end_date.month, @end_date.day, 23, 59, 59, "+00:00")
    else
      today = (Time.now - 6.hours).to_date
      start_time = today.beginning_of_day
      end_time = today.end_of_day
    end
    start_time += 6.hours
    end_time += 6.hours
    @wash_orders = WashOrder.where(created_at: start_time..end_time).order(created_at: :asc)
    respond_to do |format|
      format.html
      format.csv { send_data to_csv(@wash_orders), filename: "WO-#{Time.now.strftime('%y%m%d')}.csv" }
    end
  end

  def show
    @wash_order = WashOrder.find(params[:id])
    authorize @wash_order
  end

  def new
    @wash_order = WashOrder.new
    authorize @wash_order
  end

  def create
    @wash_order = WashOrder.new(washorder_paramas)
    authorize @wash_order
    set_wash_order_values
    if @wash_order.tool.active_wash_order?
      if @wash_order.save
        @tool.update(location:"washing")
        redirect_to tools_production_path
      else
        render :new, status: :unprocessable_entity
      end
    else
      flash[:alert] = "Tool has an open wash order"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @wash_order = WashOrder.find(params[:id])
    authorize @wash_order
  end

  def update
    @wash_order = WashOrder.find(params[:id])
    authorize @wash_order
    if @wash_order.active_sub_process
      flash[:alert] = "You can't edit an order with an active sub-process"
      render :edit, status: :unprocessable_entity
    elsif @wash_order.update(washorder_paramas)
      if @wash_order.status === "close"
        @wash_order.tool.update(location:"production")
        @wash_order.update(
          closed_by: "#{current_user.name} #{current_user.lastname}",
          closed_at: Time.current,
          time: @wash_order.total_time
        )
        @wash_order.update(wash_time: @wash_order.manual_process_start ? @wash_order.wash_time_minus_manual_process : @wash_order.time)
      end
      redirect_to tools_production_path
      flash[:notice] = "Order updated succesfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def manual_process
    @wash_order = WashOrder.find(params[:id])
    authorize @wash_order
    if @wash_order.manual_process_start.nil?
      @wash_order.update(manual_process_start: Time.current)
    else
      @wash_order.update(manual_process_end: Time.current)
    end
    redirect_to tools_production_path
  end

  private

  def washorder_paramas
    params.require(:wash_order).permit(:comments, :status)
  end

  def set_tool
    @tool = Tool.find(params[:tool_id])
  end

  def set_wash_order_values
    @wash_order.tool = @tool
    @wash_order.active = @tool.active
    @wash_order.blocked = @tool.blocked
    @wash_order.damaged = @tool.damaged
    @wash_order.created_by = "#{current_user.name} #{current_user.lastname}"
    @wash_order.status = "open"
  end

  def to_csv(wash_orders)
    attribs = [:id, :created_date, :created_time, :closed_date, :closed_time, :created_by, :wash_time, :total_time, :tool_sap, :tool_alias, :tool_bu, :tech]
    if wash_orders && wash_orders.any?
      CSV.generate(headers: true) do |csv|
        csv << attribs
        wash_orders.each do |order|
          csv << attribs.map do |attr|
            case attr
            when :created_date
              order.created_at.in_time_zone('America/Mexico_City').strftime("%Y-%m-%d")
            when :created_time
              order.created_at.in_time_zone('America/Mexico_City').strftime("%H:%M:%S")
            when :closed_date
              if order.closed_at.present?
                order.closed_at.in_time_zone('America/Mexico_City').strftime("%Y-%m-%d")
              else
                ""
              end
            when :closed_time
              if order.closed_at.present?
                order.closed_at.in_time_zone('America/Mexico_City').strftime("%H:%M:%S")
              else
                ""
              end
            when :tool_sap
              order.tool.sap
            when :tool_alias
              order.tool.alias
            when :tool_bu
              order.tool.bu
            when :tech
              order.tool.technology
            when :wash_time
              if order.wash_time.present?
                order.formatted_wash_time
              else
                ""
              end
            when :total_time
              if order.time.present?
                order.formatted_time
              else
                ""
              end
            else
              order.send(attr)
            end
          end
        end
      end
    else
      CSV.generate(headers: true) do |csv|
        csv << attribs
      end
    end
  end
end

app/views/wash_orders/edit.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Update Wash_Order</h1>
  <div class="registration-form">
    <%= simple_form_for @wash_order do |f| %>
        <h2 class="text-center">Tool: <%= @wash_order.tool.alias %>  -  <%= @wash_order.tool.sap %> </h2>
          <p><strong>Active_Cav:</strong> <%= @wash_order.active %></p>
          <p><strong>Blocked_Cav:</strong> <%= @wash_order.blocked %></p>
          <p><strong>Damaged_Cav:</strong> <%= @wash_order.damaged %></p>
          <p><strong>startd_at:</strong> <%= @wash_order.created_at.in_time_zone('America/Mexico_City').strftime('%m-%d-%y %H:%M:%S') %></p>
          <p><strong>Created_by:</strong> <%= @wash_order.created_by %></p>
          <p><strong>Closed_by:</strong> <%= @wash_order.closed_by %></p>
          <p><strong>startd_at:</strong> <%= @wash_order.created_at.in_time_zone('America/Mexico_City').strftime('%m-%d-%y %H:%M:%S') %></p>
          <p><strong>Created_by:</strong> <%= @wash_order.created_by %></p>
        <%= f.input :comments, require: true %>
        <%= f.input :status, require:true, collection: ["open", "close"] %>
        <%= f.button :submit, "Update", class:"btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/wash_orders/index.html.erb
<div class="mx-3 my-3">
    <div class="row justify-content-end">
      <div class="col-lg-6 col-md-8 my-2">
        <form class="d-flex align-items-center">
          <label for="start_date">Start:</label>
          <input type="date" name="start_date" id="start_date" class="form-control mx-2">
          <label for="end_date">End:</label>
          <input type="date" name="end_date" id="end_date" class="form-control mx-2">
          <button type="submit" class="btn btn-primary">Filter</button>
        </form>
      </div>
      <p class= "text-end" style="font-size: 12px">*Today's Orders, enter date range for custom view</p>
    </div>
    <%= link_to "Export WO CSV", wash_orders_path(start_date: @start_date, end_date: @end_date, format: :csv), class:"btn btn-primary btn-sm align-self-end" %>
  <% if @wash_orders.empty? %>
    <div class="my-3">
      <h1 class="fw-bold text-center">No Orders found</h1>
    </div>
  <% else %>
    <div class="scroll-container rounded-4 bg-light">
      <table class="table table-striped table-bordered table align-middle shadow-sm p-3 mb-5 bg-body-tertiary rounded centered-table">
        <thead>
          <tr>
          <th>ID</th>
          <th>Order_Date</th>
          <th>Max_Cap</th>
          <th>Active</th>
          <th>Blocked</th>
          <th>Damaged</th>
          <th>Status</th>
          <th>Start</th>
          <th>End</th>
          <th>Created_by</th>
          <th>SAP</th>
          <th>Alias</th>
          <th>Closed_by</th>
          <th>Wash_Time</th>
          <th>Total_Time</th>
          <th></th>
          </tr>
        </thead>
        <tbody>
        <% @wash_orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td><%= order.created_at.in_time_zone('America/Mexico_City').strftime('%m-%d-%y') %></td>
            <td><%= order.tool.capacity %></td>
            <td><%= order.active %></td>
            <td><%= order.blocked %></td>
            <td><%= order.damaged %></td>
            <td><%= order.status %></td>
            <td><%= order.created_at.in_time_zone('America/Mexico_City').strftime('%H:%M:%S') %></td>
            <td>
              <% if order.status === "close" %>
                <%= order.updated_at.in_time_zone('America/Mexico_City').strftime('%H:%M:%S') %>
              <% end %>
            </td>
            <td><%= order.created_by %></td>
            <td><%= order.tool.sap %></td>
            <td><%= order.tool.alias %></td>
            <td><%= order.closed_by %></td>
            <td>
              <% if order.wash_time.present? %>
                <%= order.formatted_wash_time%>
              <% end %>
            </td>
            <td>
              <% if order.time.present? %>
                <%= order.formatted_time%>
              <% end %>
            </td>
            <td>  <%= link_to wash_order_path(order) do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/wash_orders/new.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">New Wash_Order</h1>
  <div class="registration-form">
    <%= simple_form_for [@tool, @wash_order] do |f| %>
        <h2 class="text-center">Tool: <%= @tool.alias %> </h2>
        <%= f.input :comments, require: true %>
        <%= f.button :submit, "start_wash", class:"btn btn-primary mb-3 fw-bold" %>
    <% end %>
  </div>
</div>

app/views/wash_orders/show.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Wash_Order</h1>
  <div class="registration-form">
      <form>
        <h2 class="text-center">Tool: <%= @wash_order.tool.alias %>  -  <%= @wash_order.tool.sap %> </h2>
          <p><strong>Active_Cav:</strong> <%= @wash_order.active %></p>
          <p><strong>Blocked_Cav:</strong> <%= @wash_order.blocked %></p>
          <p><strong>Damaged_Cav:</strong> <%= @wash_order.damaged %></p>
          <p><strong>startd_at:</strong> <%= @wash_order.created_at.in_time_zone('America/Mexico_City').strftime('%m-%d-%y %H:%M:%S') %></p>
          <p><strong>Created_by:</strong> <%= @wash_order.created_by %></p>
          <p><strong>Closed_by:</strong> <%= @wash_order.closed_by %></p>
          <p><strong>Status:</strong> <%= @wash_order.status %></p>
          <p><strong>Comments:</strong> <%= @wash_order.comments %></p>
          <p><strong>Time:</strong>
            <% if @wash_order.time.present? %>
              <%= @wash_order.formatted_time %>
            <% end %>
          </p>
          <% if policy(@wash_order).edit? && @wash_order.status == "open"  %>
            <%= link_to "update", edit_wash_order_path(@wash_order), class:"btn btn-primary fw-bold" %>
          <% end %>
      </form>
  </div>
</div>

app/views/wash_orders/update.html.erb
<div class="container my-3">
  <h1 class="text-center fw-bold">Edit Wash_Order</h1>
  <div class="registration-form">
    <%= simple_form_for [@tool, @wash_order] do |f| %>
        <h2 class="text-center">Tool: <%= @tool.alias %> </h2>
        <p>
          Cavities:
        <% @blockages.each do |blockage| %>
          <%= blockage.cavity.num %>,
        <% end %>
        </p>
        <%= f.input :status, require:true, collection: ["open", "In_Process", "closed"] %>
        <%= f.input :comments, require: true %>
        <%= f.button :submit, "Send_to_Wash", class:"btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>